import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:models/models.dart';

part 'scheduling_suggestion.freezed.dart';
part 'scheduling_suggestion.g.dart';

/// Types of scheduling suggestions
enum SuggestionType {
  /// Optimal time slot for a lesson
  lessonTime,
  /// Rest day needed for horse
  horseRest,
  /// Trainer workload balancing
  trainerBalance,
  /// Arena capacity optimization
  arenaOptimization,
  /// Conflict resolution
  conflictResolution,
}

/// Priority level for suggestions
enum SuggestionPriority {
  low,
  medium,
  high,
  critical,
}

/// A smart scheduling suggestion generated by the AI system.
@freezed
sealed class SchedulingSuggestion with _$SchedulingSuggestion {
  const factory SchedulingSuggestion({
    required String id,
    required String barnId,
    required SuggestionType type,
    required SuggestionPriority priority,
    required String title,
    required String description,

    /// The suggested time slot
    @NullableTimestampConverter() DateTime? suggestedStartTime,
    @NullableTimestampConverter() DateTime? suggestedEndTime,

    /// Related entities
    String? horseId,
    String? horseName,
    String? trainerId,
    String? trainerName,
    String? clientId,
    String? clientName,
    String? lessonId,

    /// Original conflicting time (if applicable)
    @NullableTimestampConverter() DateTime? originalTime,

    /// Reason for the suggestion
    String? reason,

    /// Confidence score (0.0 to 1.0)
    @Default(0.8) double confidence,

    /// Whether the suggestion has been accepted/rejected
    @Default(false) bool isResolved,
    String? resolution, // 'accepted', 'rejected', 'modified'
    @NullableTimestampConverter() DateTime? resolvedAt,
    String? resolvedBy,

    /// Metadata
    @TimestampConverter() required DateTime createdAt,
    @NullableTimestampConverter() DateTime? expiresAt,
  }) = _SchedulingSuggestion;

  factory SchedulingSuggestion.fromJson(Map<String, dynamic> json) =>
      _$SchedulingSuggestionFromJson(json);
}

/// Horse workload analysis for smart scheduling
@freezed
sealed class HorseWorkloadAnalysis with _$HorseWorkloadAnalysis {
  const factory HorseWorkloadAnalysis({
    required String horseId,
    required String horseName,

    /// Number of rides/lessons in the past 7 days
    @Default(0) int ridesLast7Days,

    /// Total minutes of work in past 7 days
    @Default(0) int totalMinutesLast7Days,

    /// Average daily workload in minutes
    @Default(0.0) double avgDailyMinutes,

    /// Recommended max daily minutes based on horse age/fitness
    @Default(60) int recommendedMaxDailyMinutes,

    /// Days since last rest day (no rides)
    @Default(0) int daysSinceRest,

    /// Recommended rest frequency in days
    @Default(2) int recommendedRestFrequency,

    /// Whether the horse needs rest
    @Default(false) bool needsRest,

    /// Workload status
    @Default(WorkloadStatus.normal) WorkloadStatus status,

    /// Analysis timestamp
    @TimestampConverter() required DateTime analyzedAt,
  }) = _HorseWorkloadAnalysis;

  factory HorseWorkloadAnalysis.fromJson(Map<String, dynamic> json) =>
      _$HorseWorkloadAnalysisFromJson(json);
}

enum WorkloadStatus {
  underworked,
  normal,
  heavy,
  overworked,
}

/// Trainer availability slot for scheduling
@freezed
sealed class TrainerScheduleSlot with _$TrainerScheduleSlot {
  const factory TrainerScheduleSlot({
    required String trainerId,
    required String trainerName,
    @TimestampConverter() required DateTime startTime,
    @TimestampConverter() required DateTime endTime,
    @Default(true) bool isAvailable,

    /// If not available, what's scheduled
    String? bookedLessonId,
    String? bookedClientName,
    String? bookedHorseName,

    /// Score for this slot (higher = better)
    @Default(0.5) double suitabilityScore,

    /// Reasons affecting the score
    @Default(<String>[]) List<String> scoreFactors,
  }) = _TrainerScheduleSlot;

  factory TrainerScheduleSlot.fromJson(Map<String, dynamic> json) =>
      _$TrainerScheduleSlotFromJson(json);
}
