name: auth_repository
description: Dart package which manages the auth domain.
publish_to: none

environment:
  sdk: ^3.8.1

dependencies:
  authentication_client:
    path: ../authentication_client/authentication_client
  database_client:
    path: ../database_client
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  models:
    path: ../models
  storage_client:
    path: ../storage_client/storage_client

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
