name: firebase_storage_client
description: A Firebase implementation of the storage client interface
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.1

dependencies:
  firebase_auth: ^6.0.0
  firebase_storage: ^13.0.0
  flutter:
    sdk: flutter
  rxdart: ^0.28.0
  storage_client:
    path: ../storage_client


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
