name: firebase_remote_config_client
description: Firebase Remote Config client
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.1

dependencies:
  firebase_remote_config: ^6.0.0
  remote_config_client:
    path: ../remote_config_client

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
