/// Flutter icons GLIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GLIcons
///      fonts:
///       - asset: fonts/GLIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class GLIcons {
  GLIcons._();

  static const _kFontFam = 'GLIcons';
  static const String? _kFontPkg = 'app_ui';

  static const IconData firstLayout = IconData(
    0xe800,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData secondLayout = IconData(
    0xe801,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData twoFa = IconData(
    0xe802,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData add = IconData(
    0xe803,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ai_search = IconData(
    0xe804,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData ai = IconData(
    0xe805,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData alert = IconData(
    0xe806,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData attachment = IconData(
    0xe807,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData bathroom = IconData(
    0xe808,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData bedroom = IconData(
    0xe809,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData cake = IconData(
    0xe80a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData calendar = IconData(
    0xe80b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData call = IconData(
    0xe80c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData camara = IconData(
    0xe80d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData cancel = IconData(
    0xe80e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData car = IconData(
    0xe80f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData card = IconData(
    0xe810,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData check = IconData(
    0xe811,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData checkline = IconData(
    0xe812,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData chevron_down = IconData(
    0xe813,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData chevron_left = IconData(
    0xe814,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData chevron = IconData(
    0xe815,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData chevronrighg = IconData(
    0xe816,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData copy = IconData(
    0xe817,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData delete = IconData(
    0xe818,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData direction_sign = IconData(
    0xe819,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData direction = IconData(
    0xe81a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData dots = IconData(
    0xe81b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData download = IconData(
    0xe81c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData draw = IconData(
    0xe81d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData edit = IconData(
    0xe81e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData editcircle = IconData(
    0xe81f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData error = IconData(
    0xe820,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData expand = IconData(
    0xe821,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData eye_slash = IconData(
    0xe822,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData eye = IconData(
    0xe823,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData face_id = IconData(
    0xe824,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData faqs = IconData(
    0xe825,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData feedback = IconData(
    0xe826,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData file_1 = IconData(
    0xe827,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData file = IconData(
    0xe828,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData horses = IconData(
    0xe829,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData horseshoefill = IconData(
    0xe82a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData horseshoeoutline = IconData(
    0xe82b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData image = IconData(
    0xe82c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData info = IconData(
    0xe82d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData invoice = IconData(
    0xe82e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData horse = IconData(
    0xe82f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData horseshoefill_1 = IconData(
    0xe830,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData layers = IconData(
    0xe831,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData layout_left = IconData(
    0xe832,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData layout_right = IconData(
    0xe833,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData list = IconData(
    0xe834,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData location = IconData(
    0xe835,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData log_out = IconData(
    0xe836,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData mail = IconData(
    0xe837,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData management = IconData(
    0xe838,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData map = IconData(
    0xe839,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData member = IconData(
    0xe83a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData menu = IconData(
    0xe83b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData minus = IconData(
    0xe83c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData money = IconData(
    0xe83d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData no_search = IconData(
    0xe83e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData note = IconData(
    0xe83f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData notifications = IconData(
    0xe840,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData owner = IconData(
    0xe841,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData password = IconData(
    0xe842,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData pin_location_outilne = IconData(
    0xe844,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData pin = IconData(
    0xe845,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData premium = IconData(
    0xe846,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rotate_2 = IconData(
    0xe847,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rotate_clockwise_2 = IconData(
    0xe848,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sales_comparable = IconData(
    0xe849,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData seach = IconData(
    0xe84a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData security = IconData(
    0xe84b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData settings = IconData(
    0xe84c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData share = IconData(
    0xe84d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData square = IconData(
    0xe84e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData stableoutlined = IconData(
    0xe851,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData table = IconData(
    0xe853,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData taskfilled = IconData(
    0xe854,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData taskoutline = IconData(
    0xe855,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData text = IconData(
    0xe856,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData touch_id = IconData(
    0xe857,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData trash = IconData(
    0xe858,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData uplload = IconData(
    0xe859,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData userfill = IconData(
    0xe85a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData useroutline = IconData(
    0xe85b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData x = IconData(
    0xe85c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData zoom_in = IconData(
    0xe85d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData zoom_out = IconData(
    0xe85e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData invoicefilled = IconData(
    0xe85f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData stablefilled_1 = IconData(
    0xe860,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
}
