name: data_provider_client
description: A Dart Client for the HTTP API
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.1

dependencies:
  json_annotation: ^4.9.0
  models:
    path: ../../models

dev_dependencies:
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
