// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD4mFd9om7Oh7NOdNT-2bx542NA_FCfcw',
    appId: '1:930733642707:android:2dc1d64f72491d2872d526',
    messagingSenderId: '930733642707',
    projectId: 'gl-horses-develop',
    storageBucket: 'gl-horses-develop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKCzGiBg24nIY6t2sRnBJzXeTBya7_c8k',
    appId: '1:930733642707:ios:42af79c15f96d85672d526',
    messagingSenderId: '930733642707',
    projectId: 'gl-horses-develop',
    storageBucket: 'gl-horses-develop.firebasestorage.app',
    iosBundleId: 'com.smartup.glhorses.dev',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD4mFd9om7Oh7NOdNT-2bx542NA_FCfcw',
    appId: '1:930733642707:web:a01cf3e269ea2b8b72d526',
    messagingSenderId: '930733642707',
    projectId: 'gl-horses-develop',
    storageBucket: 'gl-horses-develop.firebasestorage.app',
    authDomain: 'gl-horses-develop.firebaseapp.com',
  );
}